---
- hosts: all
  become: true
  tasks:
  - name: Install mlocate
    yum: name=mlocate state=installed
  - name: Run updatedb
    command: /usr/bin/updatedb
    async: 1800
    poll: 0
    register: updatedb_task
  - name: Check on an async task
    async_status:
      jid: "{{ updatedb_task.ansible_job_id }}"
    register: job_result
    until: job_result.finished
    retries: 100
    delay: 10
  - name: print returned information
    ansible.builtin.debug:
      var: hostvars[inventory_hostname]
      verbosity: 4


